version: '3'
services:
  db:
    restart: always
    build: db/.
    environment:
      MYSQL_ROOT_PASSWORD: tiny-hippo
      MYSQL_DATABASE: TINYHIPPO
      MYSQL_USER: tiny
      MYSQL_PASSWORD: tiny-hippo    
    ports:
      - "3306:3306"
    volumes:
      - /opt/mysql_data:/var/lib/mysql
    networks:
      - db_nw

  web:
    restart: always
    build: app/.
    volumes:
      - ./app:/code/app
    working_dir: /code/app
    command: bash -c "/code/app/docker-entrypoint.sh"
    environment:
      ENV: DEV
    depends_on:
      - db
      - redis
    networks:
      - db_nw
      - web_nw
      - redis_nw
    stdin_open: true
    tty: true

  redis:
    image: "redis:alpine"
    networks:
      - redis_nw
    ports:
      - "6379:6379"
  nginx:
    # image: nginx:alpine
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    networks: 
      - web_nw

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
  redis_nw:
    driver: bridge
